name: lint
on:
  push:
    tags:
      - "*"
jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - run: |
          sudo apt-get -y update
          sudo apt-get install protobuf-compiler make -y
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          mkdir -p ../src/protobuf_compiled
          make

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yoheimuta/action-protolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
